### ISSUE TITLE
"Schema is not defined" after update

### ISSUE THREAD

**Issue by diversario** [akidee/schema.js#12]
Code:

```
var env = require('schema')('envIdentifier', {});
var schema1 = env.Schema.create({
    ...
});
```

throws

```
ReferenceError: Schema is not defined
```

at that second line.

Started after latest update.

**Comment by diversario** [comment]
Update: it was not that line, but this:

```
fallbacks: Schema.Validation.STRICT_FALLBACKS
```

but error was pointing to the line with `env.Schema.create({`.

**Comment by akidee** [comment]
It's `env.Validation.STRICT_FALLBACKS` now.
