### ISSUE TITLE
$ref and defaults

### ISSUE THREAD

**Issue by dvv** [akidee/schema.js#5]
How can I assign a default to a $ref-erencing property:

`lang: {$ref: 'Language.properties.id', default: 'ru'}` doesn't work. Assigning 'default' attribute to `id` property of Language schema works, but by sense is not right, for I want to overwrite defaults in referencing properties.

Any clue?

TIA,
--Vladimir

**Comment by akidee** [comment]
This is not implementation related. I refer you to http://json-schema.org/

**Comment by dvv** [comment]
It would be damn useful if `$ref` was dereferenced to a cloned schema if there are attributes beside `$ref`. This would allow to elegantly derive custom schemas from a base one. My case is to support default: and readonly: which I use heavily to check the data in CRUD cycle. So I have 2 schemas: one for read (which filters props the user has no access to, plus fills the default: s) and one for update (which again filters by access rules plus should delete readonly: properties)

Would be very cool to have such

**Comment by akidee** [comment]
This contradicts the standard, there is only $ref in this object. To extend, you use "extends", but take care of the current draft of "extends" - it is buggy.

Do you have taken 2 days to read the drafts carefully? ;)

But I promise: I am going to fix this soon.

**Comment by dvv** [comment]
Thanks a lot! You're doing the best json-schema tool i've ever seen

Best regards,
--Vladimir

**Comment by akidee** [comment]
And this is what my intension is.
First, I have implemented this abstract stuff in PHP, and it worked pretty well, but, of course, it was ugly.

I have updated http://github.com/akidee/schema.js/blob/master/NOTES - now we get a clearer view of what needs to be done to make schema.js even better.

**Comment by dvv** [comment]
Very good! I made a decision to make in my project all data validity checks by means of schema.js.

Staying tuned,
--Vladimir
