### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by dvv** [akidee/schema.js#7]
Please, create the subj, or schema.js dependencies are not solved by module loaders (nodules, npm)

TIA,
--Vladimir

**Comment by akidee** [comment]
Thanks for remembering! 0.1.0a is now available on npm. Please consider that the "a" means that the restruct branch soon will be merged into master with some minor changes. It will be v0.2.0 then.

Andi

**Comment by dvv** [comment]
Very well. Thanks!
