### ISSUE TITLE
Update to work with a more recent underscore.js

### ISSUE THREAD

**Issue by michaelsbradleyjr** [akidee/schema.js#8]
Presently, I can't require('schema') and require('underscore') for npm installed versions of those libraries as schema.js references an older version of underscore (which it installs automatically, as a dependency) and there is some kind of naming conflict.

My node.js script throws the following error if I require both (but I can require either apart from the other):

```
exception: ReferenceError: _ is not defined
stack: ReferenceError: _ is not defined
```

Should we expect an update soon that will make it possible to use schema.js alongside the latest release of underscore?

Thanks for a great library, schema is beyond useful.  :-)

**Comment by michaelsbradleyjr** [comment]
By the way, I'm using node v0.3.6.

**Comment by michaelsbradleyjr** [comment]
Nevermind, I confused myself:  I see that underscorex (underscorex@0.1.0) is distinct from the underscore library -- it appears to be an issue with underscorex.

**Comment by akidee** [comment]
https://github.com/akidee/underscorex/issues/issue/3

**Comment by michaelsbradleyjr** [comment]
Thanks.
